ALTER TABLE roms
DROP COLUMN IF EXISTS rom_files;

ALTER TABLE roms
ADD COLUMN IF NOT EXISTS zipped BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE roms
ADD COLUMN IF NOT EXISTS zipped_entry VARCHAR(255);
